# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64b6fdc4c6c55b189045a5633af66a2a0db1f0de5b0aeb6751af98c4ff5a5a4e597dc4a878fc87ae6867fe28c8c4b966d072ec72149da064ffb617f1935c44a1

test:
  secret_key_base: 96055f13978af1dc937ab853d6150741d57913be519a2d0c244edf634ca501dc1c7de08f938532fc6beaece4b669698623bd7e61214aa6509b175d3d5d75a3cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
